Repository ssginc-be/pjt3, pull requests merged in 2025-02, with the labels that each got.

#7 배포 CI/CD 구축
  .github/deployer.sh
  .github/workflows/dockerizer.yml
  .gitignore
  api-gateway.Dockerfile
  build.gradle
  common-service.Dockerfile
  common-service/src/main/resources/application.yml
  compose.yml
  reserve-service.Dockerfile
  service-discovery.Dockerfile
Labels: ci/cd

#8 [이용자] 채팅 송수신 기능 기본 구현
  common-service/build.gradle
  common-service/src/main/java/com/ssginc/commonservice/chat/controller/ChatController.java
  common-service/src/main/java/com/ssginc/commonservice/chat/dto/ChatDto.java
  common-service/src/main/java/com/ssginc/commonservice/chat/entity/Chat.java
  common-service/src/main/java/com/ssginc/commonservice/chat/entity/Message.java
  common-service/src/main/java/com/ssginc/commonservice/chat/repository/ChatRepository.java
  common-service/src/main/java/com/ssginc/commonservice/chat/service/ChatService.java
  common-service/src/main/java/com/ssginc/commonservice/config/WebSocketConfig.java
  common-service/src/main/resources/templates/chat/chatting.html
Labels: feat, ui

#12 Release 1.0.0-beta.2
  .github/deployer.sh
  .github/workflows/dockerizer.yml
  .gitignore
  api-gateway.Dockerfile
  build.gradle
  common-service.Dockerfile
  common-service/build.gradle
  common-service/src/main/java/com/ssginc/commonservice/chat/controller/ChatController.java
  common-service/src/main/java/com/ssginc/commonservice/chat/dto/ChatDto.java
  common-service/src/main/java/com/ssginc/commonservice/chat/entity/Chat.java
  common-service/src/main/java/com/ssginc/commonservice/chat/entity/Message.java
  common-service/src/main/java/com/ssginc/commonservice/chat/repository/ChatRepository.java
  common-service/src/main/java/com/ssginc/commonservice/chat/service/ChatService.java
  common-service/src/main/java/com/ssginc/commonservice/config/WebSocketConfig.java
  common-service/src/main/resources/application.yml
  common-service/src/main/resources/templates/chat/chatting.html
  compose.yml
  reserve-service.Dockerfile
  service-discovery.Dockerfile
Labels: feat, ci/cd
